### ISSUE TITLE
qtinter0.8 ,@qtinter.asyncslot function can't used in QMenu??

### ISSUE THREAD

**Issue by zbx911** [fancidev/qtinter#11]
self.contextMenu = QMenu(self)
self.actionRefresh = QAction("Refresh", self, priority=QAction.LowPriority)
self.actionRefresh.triggered.connect(self.actionRefreshHandler)
self.contextMenu.addAction(self.actionRefresh)

    @qtinter.asyncslot
    async def  actionRefreshHandler(self):
             pass

can you test this in example?

**Comment by fancidev** [comment]
Maybe typo? 

self.actionRefresh.triggered.connect(self.**actionRefreshHandler**)

but the slot’s name is **refreshHandler**

**Comment by zbx911** [comment]
> 

i copy code wrong！
