### ISSUE TITLE
some error on run_in_executor?

### ISSUE THREAD

**Issue by zbx911** [fancidev/qtinter#13]
class Ui_hexeditorDialog(object):
    def setupUi(self, hexeditorDialog):
        hexeditorDialog.setObjectName("hexeditorDialog")
        hexeditorDialog.resize(857, 766)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/images/ui-combo-box-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        hexeditorDialog.setWindowIcon(icon)

        self.retranslateUi(hexeditorDialog)
        QtCore.QMetaObject.connectSlotsByName(hexeditorDialog)

    def retranslateUi(self, hexeditorDialog):
        _translate = QtCore.QCoreApplication.translate
        hexeditorDialog.setWindowTitle(_translate("hexeditorDialog", "hexeditorDialog"))

class BaseDialog(QtWidgets.QDialog):
    def __init__(self,parent=None, *args):
        super(BaseDialog, self).__init__(*args)
        self.setWindowModality(True)  # 非模态

class HexEditorDialog(BaseDialog, Ui_Dialog):
    # asyncsignal()
    def __init__(self, parent=None, device=None, *args):
        super(HexEditorDialog, self).__init__(*args)

        self.setupUi(self)
        self.parent = parent
        self.device = device
        if self.device is None:
            self.parent.log("[E] device is None")
            return

async def dialog_exec_(self,dialog_class):
        def run_dialog(dialog, loop):

            dialog.activateWindow()
            dialog.setWindowState(dialog.windowState() & ~Qt.WindowMinimized | Qt.WindowActive)
            dialog.showNormal()
            # dialog.show()
            dialog.exec_()

        # if dialog_class in self.sub_dialog and self.sub_dialog[dialog_class].isActiveWindow():
        if dialog_class in self.sub_dialog:
            dialog = self.sub_dialog[dialog_class]
            dialog.activateWindow()  
            # dialog.setWindowState(dialog.windowState() & ~Qt.WindowMinimized | Qt.WindowActive)
            dialog.show()
            return

        serial = self.qcbox_devices.currentText()
        d = await self.adb.device(serial)
        dialog = dialog_class(self, d)
        loop = asyncio.get_running_loop()
        self.sub_dialog[dialog_class]=dialog

        import concurrent.futures
        with concurrent.futures.ThreadPoolExecutor() as pool:
             await loop.run_in_executor(pool, functools.partial(run_dialog, dialog), loop)
        # await loop.run_in_executor(None, functools.partial(run_dialog, dialog), loop)

if __name__ == "__main__":
    try:
        app = QApplication(sys.argv)
        QApplication.setStyle('Fusion')
        win = DataInspectorDialog()
        win.show()
        with qtinter.using_asyncio_from_qt():
            app.exec()
    except asyncio.exceptions.CancelledError:
        sys.exit(0)

**Comment by fancidev** [comment]
Hi, what error message do you get?

**Comment by zbx911** [comment]
> Hi, what error message do you get?

no error message，Process is stuck.

**Comment by fancidev** [comment]
I had a quick look at the code.

The main problem is that you call `loop.run_in_executor`. That will create a new thread to run your dialog. But all GUI dialogs should usually be run only from the main thread. So `run_in_executor` should not be used.

If you want to launch a *modal* dialog from an `async def` function, you should code like this:
```python
await qtinter.modal(dialog.exec_)()
```

If you want to launch a *modal* dialog from.a normal function, you should do
```python
dialog.exec_()
```

If you want to launch multiple *modeless* dialogs, you should call `dialog.show()`, and listen to its `finished` signal. An example:

```python
async def choose_color():
    dialog = QtWidgets.QColorDialog()
    dialog.show()
    result = await qtinter.asyncsignal(dialog.finished)  # <-- wait for signal
    if result == QtWidgets.QDialog.DialogCode.Accepted:
        return dialog.selectedColor().name()
    else:
        return None
```

**Comment by zbx911** [comment]
> I had a quick look at the code.
> 
> The main problem is that you call `loop.run_in_executor`. That will create a new thread to run your dialog. But all GUI dialogs should usually be run only from the main thread. So `run_in_executor` should not be used.
> 
> If you want to launch a _modal_ dialog from an `async def` function, you should code like this:
> 
> ```python
> await qtinter.modal(dialog.exec_)()
> ```
> 
> If you want to launch a _modal_ dialog from.a normal function, you should do
> 
> ```python
> dialog.exec_()
> ```
> 
> If you want to launch multiple _modeless_ dialogs, you should call `dialog.show()`, and listen to its `finished` signal. An example:
> 
> ```python
> async def choose_color():
>     dialog = QtWidgets.QColorDialog()
>     dialog.show()
>     result = await qtinter.asyncsignal(dialog.finished)  # <-- wait for signal
>     if result == QtWidgets.QDialog.DialogCode.Accepted:
>         return dialog.selectedColor().name()
>     else:
>         return None
> ```

i try it.
