### ISSUE TITLE
[error]  error in run Qprocess!!!!

### ISSUE THREAD

**Issue by zbx911** [fancidev/qtinter#9]
import asyncio
import functools
import os

import sys
import time

import aiofiles
import qtinter
from PyQt5 import QtCore
from PyQt5.QtCore import QObject, pyqtSignal, Qt
from PyQt5.QtGui import QTextCursor
from PyQt5.QtWidgets import QApplication
from aiofiles.os import mkdir

# from adb_gui_async.ui.logcat import Ui_logcat_Dialog
# from adb_gui_async.ui_component.BaseDialog import BaseDialog

from ui.logcat import Ui_Dialog as Ui_logcat_Dialog
from ui_component.BaseDialog import BaseDialog

class LogcatOutputDialog(BaseDialog, Ui_logcat_Dialog):
    # appendSignal = pyqtSignal(str)
    def __init__(self, parent=None, device=None, *args):
        super(LogcatOutputDialog, self).__init__(*args)
        self.parent = parent
        self.device = device
        self.setupUi(self)
        # self.textBrowserConsole.setStyleSheet("background:#f0f0f0")
        # https://blog.csdn.net/venture5/article/details/121423286
        # todo 实时显示输出, 将控制台的输出重定向到界面中
        self._process = QtCore.QProcess()

        self.pushButton_Clear.clicked.connect(self.on_clear_log)

        self.checkBox_Print.stateChanged.connect(self.on_print)

        # self.appendSignal.connect(self.update_text)
        # self.appendToTextEdit = self.appendSignal.emit

        self.f=None
    def start_log(self, program, arguments=None):
        if arguments is None:
            arguments = []

        self._process.readyReadStandardOutput.connect(self.handle_stdout)
        self._process.readyReadStandardError.connect(self.handle_stderr)
        self._process.start(program, arguments)
    @qtinter.asyncslot
    async def handle_stdout(self):
        message = self._process.readAllStandardOutput().data().decode()
        if self:
            await self.update_text(message)
    @qtinter.asyncslot
    async def handle_stderr(self):
        message = self._process.readAllStandardError().data().decode()
        if self:
            await self.update_text(message)

    async def run_logcat(self):
        # await self.device.abc_logcat(self.stdout, self.stderr)
        await self.device.abc_logcat()

    @qtinter.asyncslot
    async def  on_print(self):
        if self.checkBox_Print.checkState() == Qt.Checked:
            self.f=await  aiofiles.open(await self.generateLogFilePath(), 'a+')
            # filter="logcat -b kernel,default |grep TRACE"
            filter = "-b kernel,default"
            self.start_log("adb", ["-s", self.device.serial, "logcat", filter])

        elif self.checkBox_Print.checkState() == Qt.Unchecked:
            self._process.readyReadStandardOutput.disconnect(self.handle_stdout)
            self._process.readyReadStandardError.disconnect(self.handle_stderr)

            # if self.f is not None:
            #     await self.f.close()

    def __del__(self):
        if self.f is not None:
            self.f.close()
        self._process.close()

    def on_clear_log(self):

        self.plainTextEdit_Log.clear()

    async def generateLogFilePath(self):
        await self.parent.log("[+]","生成log文件!")
        currentPath = os.getcwd()
        if not os.path.exists(currentPath+"/logcat"):
            await mkdir(currentPath + "/logcat")
        else:
            pass
        path=os.getcwd()
        now = time.strftime("%Y-%m-%d",time.localtime(time.time()))  
        filename =path+"/logcat/"+self.device.serial+'_'+now+r".txt"          
        # logcat_file =open(filename,'w')
        return filename

    @qtinter.asyncslot
    async def update_text(self, text):
        if isinstance(text, bytes):
            text = text.decode()
        cursor=None
        if self.checkBox_Scoll.isChecked():  # todo 是否滚动
            cursor = self.plainTextEdit_Log.textCursor()
            cursor.movePosition(QTextCursor.End)

        self.plainTextEdit_Log.appendPlainText(text)
        if self.checkBox_Scoll.isChecked():
            self.plainTextEdit_Log.setTextCursor(cursor)
        self.plainTextEdit_Log.ensureCursorVisible()
        if self.checkBox_SaveFile.isChecked():
            await self.f.write(text)
    def closeEvent(self, event):

        self._process.close()
        self._process.terminate()
        event.accept()		

Task exception was never retrieved
future: <Task finished name='Task-4' coro=<LogcatOutputDialog.handle_stdout() done, defined at G:\游戏分析\Fuck_linux_kernel\adb_gui_async\ui_component\LogcatOutputDialog.py:54> exception=TypeError("object NoneType can't be used in 'await' expression")>
Traceback (most recent call last):
  File "G:\游戏分析\Fuck_linux_kernel\adb_gui_async\ui_component\LogcatOutputDialog.py", line 58, in handle_stdout
    await self.update_text(message)
TypeError: object NoneType can't be used in 'await' expression
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<LogcatOutputDialog.handle_stdout() done, defined at G:\游戏分析\Fuck_linux_kernel\adb_gui_async\ui_component\LogcatOutputDialog.py:54> exception=TypeError("object NoneType can't be used in 'await' expression")>
Traceback (most recent call last):
  File "G:\游戏分析\Fuck_linux_kernel\adb_gui_async\ui_component\LogcatOutputDialog.py", line 58, in handle_stdout
    await self.update_text(message)
TypeError: object NoneType can't be used in 'await' expression
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<LogcatOutputDialog.handle_stdout() done, defined at G:\游戏分析\Fuck_linux_kernel\adb_gui_async\ui_component\LogcatOutputDialog.py:54> exception=TypeError("object NoneType can't be used in 'await' expression")>
Traceback (most recent call last):
  File "G:\游戏分析\Fuck_linux_kernel\adb_gui_async\ui_component\LogcatOutputDialog.py", line 58, in handle_stdout

**Comment by fancidev** [comment]
Thanks for trying it out on Sunday!

I made a patch in the latest release (0.8.0) and your code should work now. Please update the package by

```
pip install -U qtinter
```

and try again.
